Add Kanagawa
Misterio77/nix-colors pull request #6
Opened 2022-01-23 13:53 UTC by NarutoXY

2022-01-23 17:04 UTC, Misterio77 requested changes
Thank you! Just a few nits before we merge

2022-01-23 17:04 UTC, Misterio77 commented on schemes/default.nix
> +  kanagawa = import ./kanagawa/kanagawa.nix;
```suggestion

  kanagawa = import ./kanagawa/kanagawa.nix;
```
This should not be grouped together with katy

2022-01-23 17:04 UTC, Misterio77 commented on schemes/kanagawa/kanagawa.nix
> +  slug = "Kanagawa";
```suggestion
  slug = "kanagawa";
```
And the slug must be all lowercase

2022-01-23 17:04 UTC, Misterio77 commented on schemes/kanagawa/kanagawa.nix
> +  author = "rebelot";
```suggestion
  author = "Tommaso Laurenzi (https://github.com/rebelot)";
```
It's better if this is more detailed, like this

2022-01-24 09:22 UTC, NarutoXY commented
Committed all the suggestions :D

2022-01-24 09:23 UTC, Misterio77 approved these changes
Looks great! Thank you :))

2022-01-24 09:23 UTC, merged